name: Tests

on:
  push:
    branches:
      - v4

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x]
        redis-version: [6.x, 5.x]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1.10.3
        with:
          redis-version: ${{ matrix.redis-version }}
          auto-start: "false"

      - name: Install Packages
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Generate lcov
        run: ./node_modules/.bin/nyc report -r lcov

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
